Repository HoloENFans/flora4fauna, pull requests merged in 2024-12, with the labels that each got.

#2 Testing out web component
  bun.lockb
  eslint.config.mjs
  index.html
  package.json
  src/components/about-modal.ts
  src/components/accountability-modal.ts
  src/components/base-modal.ts
  src/components/donate-modal.ts
  src/components/find-donation-modal.ts
  src/components/front-ui.ts
  src/components/index.ts
  src/components/mobile-nav.ts
  src/components/stats-modal.ts
  src/database.ts
  src/main.ts
  src/pocketbase.ts
  src/settings.ts
  src/stats.ts
  src/style.css
  src/tree.ts
  tailwind.config.js
Labels: Priority: High, Type: Enhancement

#8 Lazy loading screen
  index.html
  src/main.ts
Labels: Type: Feature

#9 Background
  assets/background/Background.png
  assets/branch{tps}/Branch_Big_01.png
  assets/branch{tps}/Branch_Big_02.png
  assets/branch{tps}/Branch_Cluster_01.png
  assets/branch{tps}/Branch_End.png
  assets/branch{tps}/Branch_Joint_01.png
  assets/branch{tps}/Branch_Joint_02.png
  assets/branch{tps}/Branch_Left_01.png
  assets/branch{tps}/Branch_Left_End.png
  assets/branch{tps}/Branch_Left_Root.png
  assets/branch{tps}/Branch_Med_01.png
  assets/branch{tps}/Branch_Med_02.png
  assets/branch{tps}/Branch_Right_01.png
  assets/branch{tps}/Branch_Right_End.png
  assets/branch{tps}/Branch_Right_Root.png
  assets/branch{tps}/Branch_Root.png
  assets/branch{tps}/Branch_Seed_01.png
  assets/branch{tps}/Branch_Small_01.png
  assets/branch{tps}/Branch_Small_02.png
  assets/branch{tps}/Branch_Square.png
  assets/branch{tps}/Leaf_01.png
  assets/branch{tps}/Leaf_Greyscale_01.png
  assets/fauna.png
  assets/foreground/FG_Grass_Base.png
  assets/foreground/FG_Grass_Cluster.png
  assets/foreground/Fauna+Environment.png
  assets/foreground/Fauna_Nemu.png
  assets/foreground/Grass_Base_Fauna.png
  assets/foreground/Grass_Front.png
  assets/leaf/Big_Leaf.png
  assets/leaf/Big_Leaf_Greyscale.png
  assets/smol_fauna.png
  assets/tree/Leaf_01.png
  assets/tree{tps}/BG_Sapling_01.png
  assets/tree{tps}/BG_Sapling_02.png
  assets/tree{tps}/Trunk_Base.png
  assets/tree{tps}/Trunk_Mid_01.png
  assets/tree{tps}/Trunk_Mid_01_CroppedY.png
  assets/tree{tps}/Trunk_Mid_02.png
  assets/tree{tps}/Trunk_Mid_02_CroppedY.png
  assets/tree{tps}/Trunk_Top_01.png
  assets/tree{tps}/Trunk_Top_01_CroppedY.png
  assets/ui/Wooden_Sign.png
  assets/ui/Wooden_Sign_Plain.png
  assets/unused{ignore}/Background_Blurred.png
  src/components/front-ui.ts
  src/database.ts
  src/main.ts
  src/tree.ts
  vite.config.ts
Labels: Priority: High, Type: Feature

#10 Add signs at bottom of tree
  assets/ui/ArborDayFoundation.png
  src/donationPopup.ts
  src/main.ts
Labels: Priority: Medium, Type: Feature
